from src.core.exceptions import *


class InvalidUserLoginException(AuthException): ...


class UserPermissionDeniedException(PermissionDeniedException): ...


class DetailNotFoundException(ResourceNotFoundException): ...


class TransactionsNotFoundException(ResourceNotFoundException): ...
