from src.core.handlers.exceptions import *


class InvalidUserLoginException(AuthException): ...


class UserPermissionDeniedException(PermissionDeniedException): ...


class DetailNotFoundException(ResourceNotFoundException): ...


class TransactionsNotFoundException(ResourceNotFoundException): ...
